### PR TITLE
WiP: Merge master to orocos cpp

### PR DESCRIPTION
**Pull request by planthaber**
Included: add configuration via property

### CODE REVIEW

**Comment by doudou** [comment]
I'm really not a big fan. Why don't you export the transformer data as YAML, ready to load with your tooling instead ?

**Comment by planthaber** [comment]
I don't really know, apparently the idea was to be able to ask the running task for the needed transformations. I think we use it for the cpp-based launch system we are about to release as OSS.

I think the reason is that the transformer in the rock task can be (re-)configured with which frames are needed, so the required transformations can be changed at runtime. I am currently unsure how it is handled in ruby, but I guess it must be loading all orogen models, get the transformation names and then request the according properties from the task. If it is this way, I think it is overly complicated compared to calling an operation to directly request the needed transformations.

@maltewi do you know more about where it is needed?

**Comment by maltewi** [comment]
I thought this is sorted out since.. years?

From my perspective this is not needed. The orocos_cpp/rock-runtime tooling runs with master of this package. The related merge request here where either closed (https://github.com/rock-core/drivers-orogen-transformer/pull/3) or merged (https://github.com/rock-core/drivers-orogen-transformer/pull/15).

It works like in ruby: When using transformer for wiring up port connections this is done offline. When using it for visualization, die respective information is published via transformer_broadcaster. Dynamically changing transformer configurations in between different control networks are reflected at reconfiguring transformer_broadcaster accordingly.

I wonder a bit why this pop up again. Can you check, if you have an outdated override somewhere (where?), or if there is still a feature that's not working with master (what is it?).

**Comment by planthaber** [comment]
It was in the list of the required overrides for the QT5 stack, but apparently not needed anymore, closing this

**Pull request closed without merging**
